// src/routes/about/+page.svelte
<script>
  import avatar from '$lib/assets/avatar.jpg';
  import PageContainer from '$lib/components/layouts/PageContainer.svelte';
  import Image from '$lib/components/ui/Image.svelte';
  import Link from '$lib/components/ui/Link.svelte';
</script>

<PageContainer>
  <div class="inner">
    <div class="profile">
      <Image src={avatar} alt="Yuki Yamamura's avatar" class="image" height={256} width={256} />
      <div class="name">Yuki Yamamura</div>
      <p>A software engineer @Japan</p>
    </div>
    <div class="line" aria-hidden={true}></div>
    <ul class="sns">
      <li>
        <Link href="https://github.com/example">https://github.com/example</Link>
      </li>
      <li>
        <Link href="https://x.com/example">https://x.com/example</Link>
      </li>
      <li>
        <Link href="mailto:example@exmaple.com">example@example.com</Link>
      </li>
    </ul>
  </div>
</PageContainer>

<style>
  .inner {
    margin-block: auto;
    margin-inline: auto;
  }

  .profile {
    display: flex;
    flex-direction: column;
    row-gap: 12px;
    align-items: center;
  }

  :global(.image) {
    align-self: center;
    inline-size: 256px;
    block-size: 256px;
    border-radius: 100vmax;
  }

  .name {
    align-self: center;
    font-size: 1.5rem;
  }

  .line {
    inline-size: 75%;
    block-size: 1px;
    margin-block: 12px;
    border-block-start: 1px solid;
  }

  .sns {
    padding-inline-start: 0;
  }
</style>

// src/app/about/page.tsx
import { Link } from '@/components/ui/link';

import styles from './page.module.css';

const Page = () => (
  <div className={styles.base}>
    <div className={styles.inner}>
      <div className={styles.bio}>
        <img src="/avatar.jpg" alt="" className={styles.image} />
        <div className={styles.name}>Yuki Yamamura</div>
        <div>A software engineer @Japan</div>
      </div>
      <div className={styles.line} aria-hidden />
      <div className={styles.sns}>
        <Link href="https://github.com/yuki-yamamura" className={styles.link}>
          GitHub
        </Link>
        <Link href="https://discord.gg/Tn56fqUm" className={styles.link}>
          Discord
        </Link>
      </div>
    </div>
  </div>
);

export default Page;
